# Generated by Django 5.0.7 on 2024-08-03 11:12

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stitching', '0002_btn_alter_product_original_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('details', django_jsonform.models.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Btn',
        ),
    ]
