# Generated by Django 5.0.7 on 2024-08-03 11:28

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stitching', '0003_button_delete_btn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('specifications', django_jsonform.models.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Button',
        ),
    ]
