# Generated by Django 5.0.7 on 2024-08-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stitching', '0005_button_delete_products_delete_specificationtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='button',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='button',
            name='sku',
            field=models.CharField(default='1674', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
