# Generated by Django 5.0.7 on 2024-08-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stitching', '0006_alter_button_image_alter_button_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='sku',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
    ]
