# Generated by Django 5.0.7 on 2024-08-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stitching', '0008_fabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('booking_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('preference_image', models.ImageField(blank=True, null=True, upload_to='preferences/')),
                ('note', models.TextField(blank=True, null=True)),
                ('button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stitching.button')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stitching.fabric')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stitching.product')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stitching.city')),
            ],
        ),
    ]
