# Generated by Django 5.0.7 on 2024-09-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stitching', '0012_news_alter_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
