# Generated by Django 5.0.7 on 2024-10-30 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stitching', '0013_remove_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_id',
            field=models.CharField(default=123456789, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='button',
            field=models.ForeignKey(blank=True, default=12, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stitching.button'),
        ),
        migrations.AlterField(
            model_name='button',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
