# Generated by Django 5.0.7 on 2024-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stitching', '0016_subscriber_date_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('completed', 'Completed')], default='new', max_length=10),
        ),
    ]
