# Generated by Django 5.0.7 on 2024-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stitching', '0017_jobapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='home_images/')),
                ('heading1', models.CharField(max_length=255)),
                ('image2', models.ImageField(upload_to='home_images/')),
                ('heading2', models.CharField(max_length=255)),
                ('image3', models.ImageField(upload_to='home_images/')),
                ('heading3', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
